language: node_js
node_js: stable
dist: trusty
sudo: required
cache:
  directories:
    - node_modules

addons:
  firefox: latest
  sauce_connect: true
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install -g bower polylint web-component-tester
- bower install
script:
- xvfb-run wct
- if [ ${TRAVIS_PULL_REQUEST} != false ]; then wct -s 'default'; fi
