language: node_js
node_js: stable
dist: trusty
sudo: required
addons:
  firefox: latest
  sauce_connect: true
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install -g bower polylint web-component-tester
- bower install
script:
- xvfb-run wct
- if [ ${TRAVIS_PULL_REQUEST} != false ]; then wct -s 'default'; fi
env:
  global:
  - secure: kJfT8JTvFY9Q5lrdPLvpYPgrdUL9WKtx+X7vMsDdoCCoBnPf9mUghEaRw0GQv1FRy1s97gLEsfDCnSfSMaNAXl9IMUT7w2fAFENvnPru3KBEwZqC4nmZ2Sbpzh7l1Y+z43LO1niDRq6USkbv8BU7Kxh82bi36zJ3IufMU1wRKc/b0szsBZ9ukHZoy7YZuN9kApD8D3Xg7RC48mhyCUFTw27psAkA/aCSPEpWwegqnVzfgLs76KoDEwQilGl9Oa9umvGwHy5LsM2XCSvnIE6UBxKHFrt3hiXaXYasIcPZmovge4XRkHedcO33yx6YcD1IXBmJV3kjTMx24noLpqCD0AKW9YWCgRYiLrL/ygyF/rEQAfgGUOok0uzZC4CjnfKpSYWSwv+/5ka9p5Eq01mc6spjvcJ/1V3j6TGbUuBmPxJqnESufkNETC/uYilgisBWtlUlfmIcSQdlFGI9JStpr4JuSakecvJhNjgfQ9ipepySdVClYnWzcCrx29rNcKxz7XlPbSzwu3MsqwTlavPNP06F9EI3PgTovTUPRVnMUS/xqHCuH1hceuxYr5Q4Jk/sZnaM8SxNt1X7V15uWuRECffRN/IAGs58ZIF6Ver14BOrZ1NKtsXiQ2ccoFW43RliiBSeJAiuNedjPrkStAyLuPzAljH+xnv127+AXeSZo8I=
  - secure: TLOVdS8Q9xFcjdcavRG/cxYsvnpdXnrSrDC6a6ADW+2KeSIGLB3P+kbruqjXTLuBgiGnnynwjFr4sHKLYScwujv2Kty2JOqk3z/iSZ1bh9aq1UiN7uP6qo34cGg2gNlRwgrlsP1JGW0EvWSdir11sVDZbFmBDIHqEcLATzDIpTUydXC4wk7pigooyj4RJ1d21cxCnEezOTDOuAS1KApRjF7S4WUFoAQVOWm2CCMXHgjMEg6OZl6IEkkKoomZnvSKpTu0V+g138SoKxKBwbRFklpa5TItkmM7VNEiWcmnOIa/Q7AJq6m8xYvQo6of0TO0wDX05NzrEw52X2aq0T1nMkVM4DVAaSpeSzV5ROj39mDNLSJ8ivdcvbnQQBVaqQxx3Eb8BOhBw1woH7qBt2lisno8W6p06Jwx5pLa5gn+2Gk8fLuVnp3et9iH7TmGRCOPz2VeYyprpFBCgDfj7J6vHvNe5lzVACaZQuqSlt5/jCF1RpkxvzxA2TKDPEUgVCjGW96EB++0qJVcZ49j8PQxOJgxCXmZEl4MYGiGgimcH21i2i5iU1BMFJdXK0gwGAuLq8G1m4lbGCZeFIUwYxlfrDXdehxwjPr6pwxqZS8fQ7msfPjDDYRw60sZbU9Xd68Ilux+EPBesOlMqqSX3nxRtUrUTj6CWTn1Xf/5moappBI=
