language: node_js
node_js: stable
dist: trusty
sudo: required
addons:
  firefox: latest
  sauce_connect: true
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install -g bower polylint web-component-tester
- bower install
script:
- xvfb-run wct
- if [ ${TRAVIS_PULL_REQUEST} != false ]; then wct -s 'default'; fi
env:
  global:
  - secure: GMkiGB6y0l6qYaI8D/4NrEJtRMSDwHvZeyS08U9v0ToQOooCQ4aDzH3O/xEpMY7zCNBSdKN2QThxFawPZC3kJXIXVO7V2E+sJpaXmf7tKD0AgHBKXIKMwB3arQbbXo4QB0dgA0pdKz7kmnNA/KBvLqn4GV9sEZ8EF/XsYqGstidBMrcPgbgO9lkHPxGx0MirIB6bwy0+pvxyBovFE01+/3led1eunfOmCkhStNBZ6IsXkb7hONzL7KSsWcuJ0Krmh5Ku3D6h3eTkjpvC9pq1A8TU0jl/+4FeabjlyMtl2icHvL6c5Qso/lQ6Cc9yrW/IDW/EHpze+iyiJscQdVWITkcwRPxO2id2VzFvkPzs/aVLLYFDHmJYfyrMFlUjIkOtikGL3KvYZj6BXvRVq1rfHadvcCRvQbmdIngHMcuYmvhv3CqfBUnJ2LfrzUvZ/3YteNca4z18e+1zzDPSt4y9D3DmiMXkD7ja7aLTg3/cpFQf38jsVsSAsYXxtdTOnvWpOgkhM3cydL0Qe+9Bb8yPaLcjjNgzj4OVPay+U0QQOHzC1Yy21I1VT20l0TjNT4BvDKLl+qNi1wY3wSgeXlL7aQGznB7hn1BDzz1sZKZxm0Edjjr3J0zILekGPn3URl9KvlQt8VfTnc7n74FZbqrbgJgVM86cuxYXjBSp96p1ITE=
  - secure: NIFbH66LOPqb0Ywvby/pFXxukPrtOJPDvTVLUApRrLtKj8Udlt9e3bWSxkqrllx5bueDyyw4M56clsuMLN3SDkDRhph/QMejIgUZ/dAfIiEJq10eOx02eghx+yV8/XwWC2D00AfmuRmGV9WSX5QMgxv3rVrEDyKlZ+kZyYAMoRvka7LhU/o/7Pq5oeElHr4Vq8RMbIs/mWDYRBj4NdT165cyF5rgGelTb53c48pQ6o0g/OsMoAQPMP0TiBObiEXLkmyJD/sZIhRKrV03nW524Gm0IZzx9g0QzdktxqCExg9BmYa4+Cv7yzwR5xElE8TBVTGOUNw81UrxGkOEUWJJxC8++1F9kBQijI8LjnvaB3WbQ2edaedecms0b2hg1aIH1VKRoCcn3ozTI17w+fvw9m70oiVnM/EaU2tiWAJrGduVC+Az3K+N+Vw1JbXSEhgyti/eqC4j+YGsp5UqeIVET+pC5lvbQFcAiqFfgBu6N7ttzpCvdYZkF8uRYk5Rh2Wb/rAZRZSVcm3w1x0hIUa8zwy0QiwvyDTo7Rrm9zqquYiZNehYr8n3i4k1SItiDVexqxerFAllAyBV8DBEAyARJLRapGMUWW55ZGYnCzAF+d/LEW1xlpRQOIfIgU+9q+8XD+Q7Qlfp7B0Mi73oWTB7mN+3JZ+IDpGzzruaYPt8jog=
